import type { ActivityItem, Owner, Reminder, Resource } from './types';

export const owners: Owner[] = [
  {
    id: 'owner-1',
    name: 'Nadia',
    role: 'Ops Lead',
    avatar: 'https://i.pravatar.cc/100?img=47',
  },
  {
    id: 'owner-2',
    name: 'Rafi',
    role: 'DevOps',
    avatar: 'https://i.pravatar.cc/100?img=12',
  },
  {
    id: 'owner-3',
    name: 'Sari',
    role: 'Finance',
    avatar: 'https://i.pravatar.cc/100?img=33',
  },
];

export const resources: Resource[] = [
  {
    id: 'res-1',
    type: 'domain',
    label: 'Portal Membership',
    hostname: 'member.rumahbuah.id',
    provider: 'Cloudflare Registrar',
    expiryDate: '2024-12-11',
    ownerId: 'owner-1',
    cadence: '60/30/14/7/3/1',
    status: 'due-soon',
    renewalUrl: 'https://dash.cloudflare.com/domains',
    notes: 'Pakai contact Pandi 7 hari sebelum expired.',
    lastChecked: '2024-11-15T02:10:00Z',
    tags: ['mission-critical', 'id'],
  },
  {
    id: 'res-2',
    type: 'hosting',
    label: 'Niagahoster Business',
    hostname: 'server-02',
    provider: 'Niagahoster',
    expiryDate: '2024-08-02',
    ownerId: 'owner-2',
    cadence: '30/14/7/3/1/0',
    status: 'overdue',
    renewalUrl: 'https://manage.niagahoster.co.id/invoices',
    notes: 'Migrasi ke VPS sebelum 2024-09.',
    lastChecked: '2024-08-04T05:45:00Z',
    tags: ['hosting', 'migration'],
  },
  {
    id: 'res-3',
    type: 'domain',
    label: 'Landing Page Promo',
    hostname: 'promo-lampu.com',
    provider: 'Namecheap',
    expiryDate: '2025-01-04',
    ownerId: 'owner-3',
    cadence: '60/30/14',
    status: 'healthy',
    renewalUrl: 'https://ap.www.namecheap.com/domains',
    notes: 'Auto reminder ke finance manual invoice.',
    lastChecked: '2024-12-01T01:05:00Z',
    tags: ['marketing'],
  },
  {
    id: 'res-4',
    type: 'hosting',
    label: 'Lightsail Backup Node',
    hostname: 'ls-backup-01',
    provider: 'AWS Lightsail',
    expiryDate: '2024-08-30',
    ownerId: 'owner-2',
    cadence: '14/7/3/1',
    status: 'due-soon',
    renewalUrl: 'https://lightsail.aws.amazon.com/',
    notes: 'Tagihan auto charged, tapi tetap minta notifikasi.',
    lastChecked: '2024-08-20T09:31:00Z',
    tags: ['backup', 'aws'],
  },
  {
    id: 'res-5',
    type: 'ssl',
    label: 'SSL Checkout Gateway',
    hostname: 'checkout.rumahbuah.id',
    provider: 'Cloudflare ACM',
    expiryDate: '2024-09-18',
    ownerId: 'owner-1',
    cadence: '30/14/7/3',
    status: 'due-soon',
    renewalUrl: 'https://dash.cloudflare.com/ssl-tls',
    notes: 'Butuh downtime window 15 menit jika re-issue.',
    lastChecked: '2024-08-27T04:10:00Z',
    tags: ['ssl', 'payments'],
  },
];

export const reminders: Reminder[] = [
  {
    id: 'rem-1',
    resourceId: 'res-2',
    dueInDays: -2,
    scheduledFor: '2024-08-04T09:00:00+07:00',
    severity: 'high',
    channel: 'telegram',
    message: 'Hosting Niagahoster Business sudah overdue 2 hari.',
  },
  {
    id: 'rem-2',
    resourceId: 'res-5',
    dueInDays: 12,
    scheduledFor: '2024-09-06T09:15:00+07:00',
    severity: 'medium',
    channel: 'telegram',
    message: 'SSL Checkout akan expired dalam 12 hari.',
  },
  {
    id: 'rem-3',
    resourceId: 'res-1',
    dueInDays: 30,
    scheduledFor: '2024-11-11T10:00:00+07:00',
    severity: 'low',
    channel: 'telegram',
    message: 'Domain member.rumahbuah.id 30 hari lagi.',
  },
  {
    id: 'rem-4',
    resourceId: 'res-4',
    dueInDays: 5,
    scheduledFor: '2024-08-25T09:45:00+07:00',
    severity: 'medium',
    channel: 'telegram',
    message: 'Lightsail backup node perlu dicek ulang.',
  },
];

export const activityLog: ActivityItem[] = [
  {
    id: 'act-1',
    label: 'Pengingat terkirim via Telegram',
    timestamp: '2024-08-04T09:00:00+07:00',
    actor: 'Bot Reminder',
    resourceId: 'res-2',
    action: 'reminder_sent',
  },
  {
    id: 'act-2',
    label: 'Rafi snooze 3 hari',
    timestamp: '2024-08-04T09:10:00+07:00',
    actor: 'Rafi',
    resourceId: 'res-2',
    action: 'snoozed',
  },
  {
    id: 'act-3',
    label: 'Resource domain baru ditambahkan',
    timestamp: '2024-08-01T15:40:00+07:00',
    actor: 'Nadia',
    resourceId: 'res-1',
    action: 'created',
  },
  {
    id: 'act-4',
    label: 'Reminder 30 hari dijadwalkan',
    timestamp: '2024-07-12T08:00:00+07:00',
    actor: 'Bot Reminder',
    resourceId: 'res-5',
    action: 'reminder_sent',
  },
];
